/*
 * Copyright (c) 2024 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://docs.edgeimpulse.com/page/terms-of-service) or Enterprise Terms of
 * Service (https://docs.edgeimpulse.com/page/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 07.12.2024 07:55:58

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__(section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1520;
#else
constexpr int kTensorArenaSize = 496;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,78 } };
const TfArray<1, float> quant0_scale = { 1, { 0.27366691827774048, } };
const TfArray<1, int> quant0_zero = { 1, { -83 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const ALIGN(8) int32_t tensor_data1[3] = { -547, -330, 565, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00059999607037752867, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const ALIGN(8) int8_t tensor_data2[3*3] = { 
  -68, -127, -26, 
  -82, -43, -77, 
  -10, -88, -112, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,3 } };
const TfArray<1, float> quant2_scale = { 1, { 0.010349591262638569, } };
const TfArray<1, int> quant2_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&quant2_zero, 0 };
const ALIGN(8) int32_t tensor_data3[3] = { 143, -99, -139, };
const TfArray<1, int> tensor_dimension3 = { 1, { 3 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00052412028890103102, } };
const TfArray<1, int> quant3_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&quant3_zero, 0 };
const ALIGN(16) int8_t tensor_data4[3*10] = { 
  65, 12, 123, -76, -56, 44, 97, -75, -127, 72, 
  74, 58, -78, -66, -121, 8, -2, -83, 49, -19, 
  -114, -19, 96, -1, -56, -77, -103, -45, 96, 26, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 3,10 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0066356146708130836, } };
const TfArray<1, int> quant4_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&quant4_zero, 0 };
const ALIGN(16) int32_t tensor_data5[10] = { -40, -10, 115, -332, 101, -84, 1, -13, -113, -14, };
const TfArray<1, int> tensor_dimension5 = { 1, { 10 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00066233670804649591, } };
const TfArray<1, int> quant5_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&quant5_zero, 0 };
const ALIGN(16) int8_t tensor_data6[10*30] = { 
  59, -49, -39, -4, 93, 9, 66, -66, -3, -78, 14, 9, 37, 65, 52, -49, -10, -23, -28, -2, 56, -57, 30, 14, -73, 19, 62, 45, -39, 34, 
  -34, -68, 39, 38, 32, -24, -31, -58, -56, 11, -31, -32, 38, 13, 42, 53, -30, 20, -29, -21, 2, -36, -59, 32, 64, 24, -42, -40, -41, -28, 
  -18, -57, -4, 53, -33, -35, 41, 12, -25, 27, 21, 30, -12, -51, 17, -42, 49, -61, -106, -57, -53, 41, -4, -69, 77, -23, -47, 31, -5, 67, 
  11, 5, 33, -21, -60, 45, -59, -30, -29, 16, 48, 27, -47, -58, -16, -27, -34, -36, 27, 20, 39, 52, -74, -21, -4, -53, -10, -17, -22, 19, 
  -30, 31, -57, -25, -57, 42, 19, 13, -55, 46, 54, 32, -12, 27, 29, -57, -29, 60, 22, 34, -72, -5, 58, -49, -3, -47, -22, 25, 37, -25, 
  -53, 38, -42, 24, -18, -70, -6, 43, -70, -31, 44, 33, -30, 35, -14, -40, -25, 32, -44, -6, -69, 51, 31, -5, -21, 24, -6, -10, 9, -50, 
  69, 25, -34, -53, 60, 47, 53, -23, -14, -35, 38, 22, -43, -27, 33, -11, 29, -19, -51, -34, -34, -19, -19, -59, 32, 20, -49, 42, -70, 59, 
  -8, 50, 28, 37, -7, 50, 52, -69, 68, -18, -35, 65, 36, -18, -59, 30, 50, 3, 8, 49, 6, 35, -37, -37, 41, 57, -20, 62, -54, -29, 
  41, 24, 32, 24, 61, 20, -127, -16, -18, 28, 55, 12, -3, -63, -44, 57, -52, 42, 22, -20, 60, -58, 34, 37, 72, -52, 66, -77, 15, -44, 
  26, -46, -10, -2, 47, 60, -13, 3, 46, -56, -36, 27, -45, -35, 33, -11, -13, 52, 0, 45, 65, -68, -59, 5, 24, -46, -31, -2, 20, -54, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 10,30 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0055626425892114639, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const ALIGN(16) int32_t tensor_data7[30] = { 7, -19, -11, -18, -13, -3, 76, -11, -9, -52, -17, -15, -5, -13, 75, 0, -10, -30, -71, -19, -56, 0, -6, -2, 12, 0, -60, 7, -20, 88, };
const TfArray<1, int> tensor_dimension7 = { 1, { 30 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0014480325626209378, } };
const TfArray<1, int> quant7_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const ALIGN(16) int8_t tensor_data8[30*78] = { 
  -5, 8, 72, -15, 31, 17, -31, -33, -41, -36, 38, -1, -22, -32, -9, -60, -12, 29, -23, 27, 0, -47, -46, 35, -38, -45, -63, -37, -36, 9, 66, -1, -32, 9, -51, -17, -44, 32, 24, 29, -8, 50, -43, -7, 8, 28, 4, 42, -18, -10, -19, 20, -39, 14, 33, 8, -18, 26, -9, -20, 13, 40, 34, -11, 39, -6, -25, 61, 7, 16, -16, 1, -25, 1, 12, 11, -26, 6, 
  -44, 18, 2, -39, 15, -12, 46, 43, 12, 46, -18, -13, 50, 0, -2, 40, 16, 15, 37, 50, -2, -4, 48, 17, -30, 17, -21, 28, 34, -11, -10, 15, 9, 1, 0, 19, -1, 31, 40, 4, -7, 29, -13, 27, 39, -5, -6, -29, 32, -21, 41, 25, -3, 6, -39, -42, 15, -34, -27, 0, 19, -30, 15, 13, -16, 29, -34, -4, -5, 28, 26, 10, -2, -32, -33, 23, -7, -23, 
  26, -40, -30, 24, 24, -40, -1, -7, -29, 26, 34, 9, 4, -14, -42, -28, 2, -14, 25, 40, -19, 13, -29, 30, -35, -26, -36, -5, -41, -24, -11, 44, 19, 47, -7, -41, 26, -40, 9, -10, 40, -29, 5, 5, 12, 20, -12, 3, 6, 31, -35, -14, -24, -37, -21, 34, 1, 36, 2, 5, -28, 43, -13, -28, 17, 2, 12, -28, -25, 12, -14, 0, 7, 10, 26, 4, -24, 10, 
  -40, -40, 18, 35, -7, 46, -32, 13, 26, 17, -5, -39, 20, -20, 16, -9, 22, -46, 31, -2, -14, -38, -14, -1, 48, 2, 27, 42, -6, -36, -37, 3, 32, 32, 4, -28, 16, -12, -38, 19, 39, -11, 27, 25, 30, 40, -35, -32, -19, -3, 20, -19, 14, -25, 30, -17, -10, 12, -12, 3, 23, 14, 11, -37, -21, 39, -11, 9, 31, -34, 2, 5, 13, 24, 12, -22, 8, 29, 
  9, -28, 21, 18, 56, 25, 30, 45, -28, 44, 26, -36, -2, -106, 37, -31, 12, 14, 21, 24, 4, -40, -44, -17, -25, -1, -40, -100, -49, 49, 2, -26, -17, -30, 19, 4, -21, -37, 25, 46, -63, 59, 22, -16, -10, 38, 3, 16, 43, -8, 27, -7, -84, -28, -3, -39, 8, -40, -37, -42, -21, 10, 22, -47, 2, -17, -43, -15, 6, 32, -21, 27, -31, -28, -1, 37, 11, 27, 
  -13, 38, -2, -42, 4, 8, 11, -2, -42, 22, 0, 8, -12, 26, -37, -35, 31, 0, -5, -7, -8, -14, -26, -2, 31, -40, 38, 25, -31, -32, -41, -39, 0, 32, -5, 32, 21, -24, -4, -32, 11, -27, -35, 6, -15, -25, 21, -37, 31, 39, -27, -18, 28, 16, 18, 5, -4, 35, -2, 26, 6, 44, 35, 43, -5, 22, 27, 34, 34, -16, 8, 8, 16, -24, -3, -42, 32, -27, 
  85, -75, -60, 58, -8, -31, 2, -48, -10, 8, -20, -50, 29, 63, 24, -15, 2, -23, -16, -15, 42, 7, -2, -14, -42, -40, 119, -10, -6, 53, -23, 51, 8, -9, 41, -7, 14, -45, 34, 79, -22, 16, -7, -19, -46, -24, -35, -49, -26, 31, 20, -31, 90, 1, 18, -28, -23, 33, 13, 43, -29, 47, 51, 18, -12, 54, -6, -3, 11, -14, -8, 20, -25, -27, 18, 34, 14, 11, 
  32, 24, 34, 29, 11, 42, 42, -10, -10, 37, -37, -26, -25, -24, -28, -32, -14, -35, 17, 2, 15, -28, -33, 9, -3, -18, -15, -36, 37, -15, -3, 9, -21, 27, -7, 46, -9, -28, 35, -10, -30, -32, -36, -11, 16, 6, 50, 39, -3, 46, 13, -30, -23, -34, -41, -43, 9, 47, 25, 15, -6, 48, -20, 37, -9, -16, 42, 38, -5, -28, -10, -30, 47, -38, -30, 40, 43, 19, 
  22, -9, -8, 19, -8, -2, -4, -38, 28, -29, -16, 5, 46, 15, 27, -27, 25, -39, -1, -37, 27, -17, 2, 46, -36, -27, 2, -31, -40, 20, 11, 47, -21, -38, -41, 22, 25, -29, 23, -13, 29, -21, -20, 20, 41, -33, -20, 30, 10, -18, -37, 42, -26, 15, -23, 36, 34, 11, 19, 0, 3, 38, -7, -29, 43, 7, -23, -41, -23, 0, 34, -21, 13, 27, 32, -41, 37, -30, 
  -84, 68, -18, -42, -66, -15, -47, -32, -36, 8, 42, 8, 40, -18, 9, 63, 6, -31, 2, 9, -19, 11, 4, 11, 39, 19, -32, 22, -14, -11, -83, -48, 33, 2, 47, -31, -20, -14, 14, -82, -31, 28, 25, -36, -44, -33, 16, -42, 38, -9, -35, -38, -72, 1, 30, -3, -18, 15, -23, 13, 34, 5, -10, 9, -4, -70, -16, -25, -39, -22, -3, -42, 19, 28, -22, -36, 38, 8, 
  40, -8, -51, 17, 21, 19, 20, 20, 17, -5, -21, 37, 20, 36, 18, 2, 30, -24, -9, -34, -37, 32, -5, 24, -8, 1, 11, -1, -4, -42, 27, 44, 31, -3, -22, -4, 37, 46, -14, 23, 12, 6, 26, -31, -35, 42, 17, -33, -5, -5, 44, 25, 19, 13, -28, 9, -20, -39, 16, -36, 4, -17, -18, -37, -19, -35, 21, -40, 16, -16, -16, 6, 38, 39, 6, 33, -37, -15, 
  -6, 37, -15, 4, 43, 24, -6, 23, 33, 32, 25, 26, 44, -7, -8, -6, 9, -10, 26, -28, 1, 43, -13, -9, -26, 16, 23, -19, 32, 23, -12, -26, -33, -35, 34, -12, 45, -37, -3, -35, 33, -14, -16, -2, 33, 29, -5, -20, -20, 11, 17, -20, 19, -6, 44, -5, -44, -4, 25, -6, 27, 44, -28, 30, 24, 7, -9, 41, 29, -31, 22, -23, 5, -8, 14, 18, -35, 16, 
  -21, -38, -11, -25, -28, 43, 23, 9, 12, -24, 34, 27, 38, 43, 23, -33, 20, 37, -20, -33, -17, 24, 41, -13, 37, 27, -28, 22, -36, 14, -18, -34, -5, 24, -37, 1, -28, 6, 15, -12, -14, -5, 28, 24, 31, -12, 32, -41, 22, -6, -42, 25, -38, 18, 20, -3, 39, -9, -24, 2, -30, 12, 9, 32, 18, 15, -9, -36, 19, 16, -36, 33, 24, -19, -13, -33, -28, 23, 
  10, -22, -4, 22, -37, 26, 15, 40, 44, 24, -27, -17, -31, -29, -33, -16, -23, -33, 42, 33, 18, 41, -38, 10, 24, 13, -14, 32, 30, 39, -20, -24, 48, -24, 25, -40, 45, -33, 35, -5, 0, 45, -38, -41, 40, -23, 47, -18, 32, 14, -28, 49, 21, 8, 23, -17, 21, 1, 42, -13, 8, -32, 28, -12, -15, 34, -19, -5, 7, -22, 24, -7, -8, -32, -35, 37, -24, -35, 
  99, -30, -7, -11, -17, -21, 12, -2, -49, -44, -30, 14, 10, 68, 47, -32, -18, 37, -18, -22, 53, 43, 28, -24, -39, 5, 29, 16, -53, 48, 45, 39, -35, 32, 20, -14, -37, 22, -17, 74, -2, 29, 54, 28, 31, -51, 12, 0, 27, 11, 14, -23, 65, 20, 7, -19, 2, 10, 4, -16, -19, 13, 33, 11, 40, 30, 46, -31, -20, 31, -18, -13, -20, -31, -8, -1, -39, -21, 
  0, 8, -42, -35, -5, -17, 15, -16, -25, 8, 34, 13, 15, -34, 37, -22, 10, 12, -16, 43, 12, 34, 23, -41, 0, 18, 39, 17, 13, 8, -27, -29, -32, 39, -4, -18, 18, 15, 19, 3, 1, 29, -19, 0, 7, 38, 28, -20, 36, -44, 32, -7, 37, -34, -26, 35, 44, 13, 23, -8, -1, -27, 28, -4, -37, -1, 20, 13, 42, 10, -28, -29, 44, -5, -37, 25, 26, 22, 
  -1, -14, -10, -46, -17, -13, -36, -1, 13, 20, 19, -20, 22, -21, -24, 22, 15, 39, 37, 15, 19, 4, -23, 29, 16, -33, 1, 12, -1, -24, -38, -21, 0, -26, -3, 30, -3, 7, -6, -17, -27, 30, 2, 13, 4, -30, 44, 42, -20, 15, 26, 37, -26, 33, 41, 11, -4, 30, -24, -16, 8, -15, 10, -39, 7, -41, -20, -23, -10, 40, 34, -27, -5, 1, 14, -41, -37, 27, 
  -9, 17, 25, 6, -19, -5, 3, 51, -7, -21, -6, -15, 49, 34, -20, -7, -30, -14, 23, 2, 2, 17, 19, -33, 50, 38, -38, 32, 23, 11, -29, -28, -25, -22, -17, 15, 21, -30, -31, -44, 14, 29, 34, 7, 4, -12, -4, 16, 37, 8, 19, 33, 31, 43, -33, -10, 18, 27, 19, -7, 8, 14, -14, -11, 27, 1, -37, 27, -5, -8, -36, -30, 21, -17, -11, 29, -21, 41, 
  -102, 56, -34, 17, -21, 1, -11, 37, -28, 20, -10, -6, -11, -40, 22, 13, -31, 36, -26, -49, 11, -13, -42, -12, 13, -28, -95, -54, -5, -48, -6, -17, -41, -46, -41, -28, 29, 9, -24, -64, -18, 47, 23, -38, 50, 38, 53, 1, 49, -4, 22, -5, -87, -18, 27, -37, 14, -2, 5, 25, -41, -39, -19, -10, 20, -53, -29, -5, -7, -5, 1, 6, 4, -18, 11, 18, -27, 20, 
  -5, -34, -34, 22, 10, -19, 36, -25, 36, -23, -13, 31, -18, -12, -43, 32, -10, 0, -13, 26, -25, -27, -22, 19, -35, -1, -8, 23, -1, -22, -38, 24, 2, 29, 26, -36, 26, 30, -32, 11, -33, -28, 12, -11, -1, -25, -21, 35, -8, -3, 20, -7, -40, 24, 0, -29, -10, -24, 1, 14, -36, -7, -4, 46, -24, -37, -25, -30, 25, 3, 33, -15, 2, 26, 39, -14, 25, 41, 
  -69, 57, 56, -12, -7, 6, 4, 21, -22, 30, 21, 12, -11, -127, 28, 27, 41, 18, -47, 14, -5, -51, -52, 32, 24, -42, -69, -56, -16, -8, 3, -58, -43, -27, 5, -12, 21, -34, 38, -36, -35, 63, -26, -54, 27, 34, 29, 22, 8, 12, 40, -11, -47, -34, 26, -44, 4, -19, -37, -26, -14, 17, -14, -9, 15, -115, -5, 51, 11, 18, -15, -40, -21, -12, 6, 15, 34, -10, 
  -3, 39, -13, -39, 13, 32, -28, 41, 8, -16, 34, -16, -26, -10, 36, 2, 21, 28, -11, 17, 41, 2, 30, -10, -4, 11, -18, 32, 31, -23, 32, 20, 0, -33, 2, 15, -44, 22, 37, -35, 30, -1, -11, 26, -44, -9, 40, 1, -3, 35, -14, 36, 39, 20, -22, -24, 3, -29, 8, 28, 14, -43, 2, 13, -36, -7, 9, -3, -6, 27, 32, 43, -8, -9, 43, 14, 38, -41, 
  -53, 32, 38, -34, 51, -45, -43, -46, 16, -19, 10, -17, 16, -34, 7, 38, -3, 23, -46, -34, 7, -62, -25, 13, -17, -51, -36, -14, -8, -32, -1, 2, -31, 10, -25, -7, -50, -42, -7, -12, -35, -3, -24, -6, -31, -1, -4, -21, 38, 7, -43, 31, -78, -2, 30, 25, 5, -55, -49, 13, 23, -5, 25, -59, 4, -26, -48, 41, -27, 9, 28, 23, -19, -14, -5, -36, -51, -31, 
  23, -24, -4, 42, 42, -5, 37, 13, 29, -7, -32, -6, 29, -34, -28, -14, 22, -30, 38, 5, 20, -31, 28, 12, -41, 37, -36, 23, 31, 37, -2, 26, 22, 16, -7, -20, -32, 9, -16, -8, 15, -7, -30, 33, -36, 10, 27, -7, -30, 22, -9, -19, 43, -18, 31, -16, -36, 34, 28, -42, 16, -28, 38, -30, -7, 0, -14, 38, -26, -27, 7, -3, 14, 30, 0, 15, 41, 26, 
  7, -9, -46, -41, -25, 7, -23, -51, -24, -48, 20, 0, -15, 58, -11, 56, -19, -31, -52, -20, -31, -21, -16, -31, -41, 35, 19, 75, -20, -24, 8, -36, 22, -13, -36, -11, 38, 36, 36, -44, -23, -36, 6, 36, 31, -20, -50, -38, 4, 26, -25, -2, -3, 43, -1, -11, -11, 26, 23, 2, -6, -16, 3, -9, -18, 48, -2, 12, 1, -17, -48, -46, 7, -25, -32, 18, -9, 36, 
  33, -33, -15, 12, 44, 16, -41, 17, 20, 21, -40, 20, 4, -40, -4, 19, -11, -20, -21, -24, -5, -16, 10, 9, -26, 11, 30, -21, -12, 31, -33, -11, 28, 18, 15, 38, 26, 38, 25, 37, -42, 8, -12, 18, 35, 4, 41, 36, -32, 18, -5, 10, 0, -31, -22, 41, -34, 4, 43, 44, 3, 9, 2, 31, 14, 23, -6, 38, -25, 30, 43, 17, 24, 13, 13, 8, 8, -15, 
  -84, 27, 25, -13, 47, 19, -1, -8, 31, -7, -9, -10, 44, -123, -38, -1, 1, 25, 10, 8, -65, 15, -49, -34, 8, -29, -94, -51, 1, -1, 59, -64, -28, -15, -54, -44, -14, -13, 17, -75, -16, 7, -2, 3, 37, 10, 23, 6, 38, 42, 27, 25, -99, -8, 33, -29, -15, -7, -29, -19, 19, 32, -30, -40, -41, -42, -32, 15, -21, 42, -8, 38, -6, 20, 30, -51, -20, -13, 
  -31, 22, 22, -7, 20, 17, -8, 43, 17, -32, -15, 11, 40, 50, -14, 19, 48, -21, -35, -19, 46, 5, -13, 45, 14, 33, 8, -37, 56, 7, 4, 47, 26, -16, -4, 28, -23, 37, 33, -16, -6, 8, 29, 32, -17, 14, -28, -17, 17, 20, -16, -32, 50, -32, 12, 14, -35, -13, 34, 23, -34, -36, -30, 29, -32, 53, -29, 20, -35, -20, -19, 43, -15, -39, 8, 3, -16, 32, 
  39, 26, -48, -1, -29, 4, 9, -11, -11, -28, 24, -21, 15, -26, 37, 30, 20, -5, 42, -25, -36, -22, -31, 40, 43, -29, -25, 10, -24, -3, -17, 16, 19, 8, 50, -20, 27, -23, 1, 30, -10, -28, -1, -25, 37, 8, -13, 29, -30, -36, -26, 14, 35, 13, -30, -6, 6, 43, 31, -30, -35, 33, 39, -27, 16, 40, -28, 44, 16, -23, -6, -26, 2, -25, 13, -18, 47, 26, 
  81, -39, -46, 4, -6, 25, -46, 21, -26, -18, -22, -56, -46, 52, 26, -58, 46, -38, 15, 47, -3, 42, 31, 12, 29, -2, 83, -28, 11, 13, 25, 24, -27, 16, -41, 13, 4, 17, -47, 86, -15, -54, 22, 5, -26, -47, -46, 11, -19, -23, 28, -61, 94, 34, -55, -18, 37, 38, 19, -2, 15, -31, 11, -29, -37, 111, 27, 21, 0, -9, -50, -37, 10, 38, -29, -29, 28, -13, 
};
const TfArray<2, int> tensor_dimension8 = { 2, { 30,78 } };
const TfArray<1, float> quant8_scale = { 1, { 0.0052912225946784019, } };
const TfArray<1, int> quant8_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,30 } };
const TfArray<1, float> quant9_scale = { 1, { 0.11906871944665909, } };
const TfArray<1, int> quant9_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<2, int> tensor_dimension10 = { 2, { 1,10 } };
const TfArray<1, float> quant10_scale = { 1, { 0.078985944390296936, } };
const TfArray<1, int> quant10_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const TfArray<2, int> tensor_dimension11 = { 2, { 1,3 } };
const TfArray<1, float> quant11_scale = { 1, { 0.057972922921180725, } };
const TfArray<1, int> quant11_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&quant11_zero, 0 };
const TfArray<2, int> tensor_dimension12 = { 2, { 1,3 } };
const TfArray<1, float> quant12_scale = { 1, { 0.077487453818321228, } };
const TfArray<1, int> quant12_zero = { 1, { 127 } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&quant12_zero, 0 };
const TfArray<2, int> tensor_dimension13 = { 2, { 1,3 } };
const TfArray<1, float> quant13_scale = { 1, { 0.00390625, } };
const TfArray<1, int> quant13_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&quant13_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,8,7 } };
const TfArray<1, int> outputs0 = { 1, { 9 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 9,6,5 } };
const TfArray<1, int> outputs1 = { 1, { 10 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 10,4,3 } };
const TfArray<1, int> outputs2 = { 1, { 11 } };
const TfLiteFullyConnectedParams opdata3 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs3 = { 3, { 11,2,1 } };
const TfArray<1, int> outputs3 = { 1, { 12 } };
const TfLiteSoftmaxParams opdata4 = { 1 };
const TfArray<1, int> inputs4 = { 1, { 12 } };
const TfArray<1, int> outputs4 = { 1, { 13 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 78, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 9, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 300, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 120, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 2340, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 80), (TfLiteIntArray*)&g0::tensor_dimension9, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension10, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension11, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension12, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension13, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[5] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[5] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 14, };
const size_t tflNodes_subgraph_index[] = {0, 5, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  13, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_4_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 14;
  for (size_t i = 0; i < 14; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_4_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_4_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_4_invoke() {
  for (size_t i = 0; i < 5; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_4_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
